package code

var enUSText = map[int]string{
	ServerError:        "Internal server error",
	TooManyRequests:    "Too many requests",
	ParamBindError:     "Parameter error",
	AuthorizationError: "Authorization error",
	UrlSignError:       "URL signature error",
	CacheSetError:      "Failed to set cache",
	CacheGetError:      "Failed to get cache",
	CacheDelError:      "Failed to del cache",
	CacheNotExist:      "Cache does not exist",
	ResubmitError:      "Please do not submit repeatedly",
	HashIdsEncodeError: "HashID encryption failed",
	HashIdsDecodeError: "HashID decryption failed",
	RBACError:          "No access",
	RedisConnectError:  "Failed to connection Redis",
	MySQLConnectError:  "Failed to connection MySQL",
	WriteConfigError:   "Failed to write configuration file",
	SendEmailError:     "Failed to send mail",
	MySQLExecError:     "SQL execution failed",
	GoVersionError:     "Go Version mismatch",
	SocketConnectError: "Socket not connected",
	SocketSendError:    "Socket message sending failed",

	UserCreateError:             "Failed to create user",
	UserListError:               "Failed to get user list",
	UserDeleteError:             "Failed to delete user",
	UserUpdateError:             "Failed to update user",
	UserResetPasswordError:      "Reset password failed",
	UserLoginError:              "Login failed",
	UserLogOutError:             "Exit failed",
	UserModifyPasswordError:     "Failed to modify password",
	UserModifyPersonalInfoError: "Failed to modify personal information",
	UserOfflineError:            "Offline administrator failed",
	UserDetailError:             "Failed to get personal information",

	PostCreateError: "Failed to create post",
	PostUpdateError: "Failed to update post",
	PostDeleteError: "Failed to delete post",
	PostListError:   "Failed to get post list",
	PostDetailError: "Failed to get post details",

	CommentCreateError: "Failed to create post comments",
	CommentListError:   "Failed to get post comments list",
}
