package code

var zhCNText = map[int]string{
	ServerError:           "内部服务器错误",
	TooManyRequests:       "请求过多",
	ParamBindError:        "参数信息错误",
	AuthorizationNotFound: "签名信息不能为空",
	AuthorizationError:    "签名信息错误",
	AuthorizationInvalid:  "未知签名",
	UrlSignError:          "参数签名错误",
	CacheSetError:         "设置缓存失败",
	CacheGetError:         "获取缓存失败",
	CacheDelError:         "删除缓存失败",
	CacheNotExist:         "缓存不存在",
	ResubmitError:         "请勿重复提交",
	HashIdsEncodeError:    "HashID 加密失败",
	HashIdsDecodeError:    "HashID 解密失败",
	RBACError:             "暂无访问权限",
	RedisConnectError:     "Redis 连接失败",
	MySQLConnectError:     "MySQL 连接失败",
	WriteConfigError:      "写入配置文件失败",
	SendEmailError:        "发送邮件失败",
	MySQLExecError:        "SQL 执行失败",
	GoVersionError:        "Go 版本不满足要求",
	SocketConnectError:    "Socket 未连接",
	SocketSendError:       "Socket 消息发送失败",

	UserCreateError:             "创建用户失败",
	UserListError:               "获取用户列表失败",
	UserDeleteError:             "删除用户失败",
	UserUpdateError:             "更新用户失败",
	UserResetPasswordError:      "重置密码失败",
	UserLoginError:              "登录失败",
	UserLogOutError:             "退出失败",
	UserModifyPasswordError:     "修改密码失败",
	UserModifyPersonalInfoError: "修改个人信息失败",
	UserOfflineError:            "下线用户失败",
	UserDetailError:             "获取个人信息失败",

	PostCreateError: "创建文章失败",
	PostUpdateError: "更新文章失败",
	PostDeleteError: "删除文章失败",
	PostListError:   "获取文章列表失败",
	PostDetailError: "获取文章详情失败",

	CommentCreateError: "创建文章评论失败",
	CommentListError:   "查询评论列表后台任务失败",
}
